id = "mixin"
version = "0.1.0"
namespace = "com.github.glassmc.mixin"

internal_loader = "MixinInternalLoader"

implementations = [
    "client"
]

[listeners]
initialize = [
    "MixinInitializeListener"
]